/* tslint:disable */
/* eslint-disable */
/**
 * Spring-Adam-Store
 * Api Service
 *
 * The version of the OpenAPI document: v1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


import type { Configuration } from '../configuration';
import type { AxiosPromise, AxiosInstance, RawAxiosRequestConfig } from 'axios';
import globalAxios from 'axios';
// Some imports not used depending on template conditions
// @ts-ignore
import { DUMMY_BASE_URL, assertParamExists, setApiKeyToObject, setBasicAuthToObject, setBearerAuthToObject, setOAuthToObject, setSearchParams, serializeDataIfNeeded, toPathString, createRequestFunction } from '../common';
// @ts-ignore
import { BASE_PATH, COLLECTION_FORMATS, type RequestArgs, BaseAPI, RequiredError, operationServerMap } from '../base';
// @ts-ignore
import type { ApiResponseListChatMessageResponse } from '../models';
/**
 * ChatMessageControllerApi - axios parameter creator
 * @export
 */
export const ChatMessageControllerApiAxiosParamCreator = function (configuration?: Configuration) {
    return {
        /**
         * Lấy danh sách tin nhắn  trong một cuộc trò chuyện
         * @summary Fetch all messages for conversationId
         * @param {string} conversationId 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        getMessages: async (conversationId: string, options: RawAxiosRequestConfig = {}): Promise<RequestArgs> => {
            // verify required parameter 'conversationId' is not null or undefined
            assertParamExists('getMessages', 'conversationId', conversationId)
            const localVarPath = `/v1/private/messages`;
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }

            const localVarRequestOptions = { method: 'GET', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;

            // authentication bearerAuth required
            // http bearer authentication required
            await setBearerAuthToObject(localVarHeaderParameter, configuration)

            if (conversationId !== undefined) {
                localVarQueryParameter['conversationId'] = conversationId;
            }


    
            setSearchParams(localVarUrlObj, localVarQueryParameter);
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};

            return {
                url: toPathString(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
    }
};

/**
 * ChatMessageControllerApi - functional programming interface
 * @export
 */
export const ChatMessageControllerApiFp = function(configuration?: Configuration) {
    const localVarAxiosParamCreator = ChatMessageControllerApiAxiosParamCreator(configuration)
    return {
        /**
         * Lấy danh sách tin nhắn  trong một cuộc trò chuyện
         * @summary Fetch all messages for conversationId
         * @param {string} conversationId 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async getMessages(conversationId: string, options?: RawAxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<ApiResponseListChatMessageResponse>> {
            const localVarAxiosArgs = await localVarAxiosParamCreator.getMessages(conversationId, options);
            const localVarOperationServerIndex = configuration?.serverIndex ?? 0;
            const localVarOperationServerBasePath = operationServerMap['ChatMessageControllerApi.getMessages']?.[localVarOperationServerIndex]?.url;
            return (axios, basePath) => createRequestFunction(localVarAxiosArgs, globalAxios, BASE_PATH, configuration)(axios, localVarOperationServerBasePath || basePath);
        },
    }
};

/**
 * ChatMessageControllerApi - factory interface
 * @export
 */
export const ChatMessageControllerApiFactory = function (configuration?: Configuration, basePath?: string, axios?: AxiosInstance) {
    const localVarFp = ChatMessageControllerApiFp(configuration)
    return {
        /**
         * Lấy danh sách tin nhắn  trong một cuộc trò chuyện
         * @summary Fetch all messages for conversationId
         * @param {ChatMessageControllerApiGetMessagesRequest} requestParameters Request parameters.
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        getMessages(requestParameters: ChatMessageControllerApiGetMessagesRequest, options?: RawAxiosRequestConfig): AxiosPromise<ApiResponseListChatMessageResponse> {
            return localVarFp.getMessages(requestParameters.conversationId, options).then((request) => request(axios, basePath));
        },
    };
};

/**
 * Request parameters for getMessages operation in ChatMessageControllerApi.
 * @export
 * @interface ChatMessageControllerApiGetMessagesRequest
 */
export interface ChatMessageControllerApiGetMessagesRequest {
    /**
     * 
     * @type {string}
     * @memberof ChatMessageControllerApiGetMessages
     */
    readonly conversationId: string
}

/**
 * ChatMessageControllerApi - object-oriented interface
 * @export
 * @class ChatMessageControllerApi
 * @extends {BaseAPI}
 */
export class ChatMessageControllerApi extends BaseAPI {
    /**
     * Lấy danh sách tin nhắn  trong một cuộc trò chuyện
     * @summary Fetch all messages for conversationId
     * @param {ChatMessageControllerApiGetMessagesRequest} requestParameters Request parameters.
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof ChatMessageControllerApi
     */
    public getMessages(requestParameters: ChatMessageControllerApiGetMessagesRequest, options?: RawAxiosRequestConfig) {
        return ChatMessageControllerApiFp(this.configuration).getMessages(requestParameters.conversationId, options).then((request) => request(this.axios, this.basePath));
    }
}

