/* tslint:disable */
/* eslint-disable */
/**
 * Spring-Adam-Store
 * Api Service
 *
 * The version of the OpenAPI document: v1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


import type { Configuration } from '../configuration';
import type { AxiosPromise, AxiosInstance, RawAxiosRequestConfig } from 'axios';
import globalAxios from 'axios';
// Some imports not used depending on template conditions
// @ts-ignore
import { DUMMY_BASE_URL, assertParamExists, setApiKeyToObject, setBasicAuthToObject, setBearerAuthToObject, setOAuthToObject, setSearchParams, serializeDataIfNeeded, toPathString, createRequestFunction } from '../common';
// @ts-ignore
import { BASE_PATH, COLLECTION_FORMATS, type RequestArgs, BaseAPI, RequiredError, operationServerMap } from '../base';
// @ts-ignore
import type { ApiResponseColorResponse } from '../models';
// @ts-ignore
import type { ApiResponsePageResponseColorResponse } from '../models';
// @ts-ignore
import type { ApiResponseVoid } from '../models';
// @ts-ignore
import type { ColorRequest } from '../models';
/**
 * ColorControllerApi - axios parameter creator
 * @export
 */
export const ColorControllerApiAxiosParamCreator = function (configuration?: Configuration) {
    return {
        /**
         * 
         * @param {ColorRequest} colorRequest 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        create7: async (colorRequest: ColorRequest, options: RawAxiosRequestConfig = {}): Promise<RequestArgs> => {
            // verify required parameter 'colorRequest' is not null or undefined
            assertParamExists('create7', 'colorRequest', colorRequest)
            const localVarPath = `/v1/admin/colors`;
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }

            const localVarRequestOptions = { method: 'POST', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;

            // authentication bearerAuth required
            // http bearer authentication required
            await setBearerAuthToObject(localVarHeaderParameter, configuration)


    
            localVarHeaderParameter['Content-Type'] = 'application/json';

            setSearchParams(localVarUrlObj, localVarQueryParameter);
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};
            localVarRequestOptions.data = serializeDataIfNeeded(colorRequest, localVarRequestOptions, configuration)

            return {
                url: toPathString(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
        /**
         * 
         * @param {number} id 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        delete9: async (id: number, options: RawAxiosRequestConfig = {}): Promise<RequestArgs> => {
            // verify required parameter 'id' is not null or undefined
            assertParamExists('delete9', 'id', id)
            const localVarPath = `/v1/admin/colors/{id}`
                .replace(`{${"id"}}`, encodeURIComponent(String(id)));
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }

            const localVarRequestOptions = { method: 'DELETE', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;

            // authentication bearerAuth required
            // http bearer authentication required
            await setBearerAuthToObject(localVarHeaderParameter, configuration)


    
            setSearchParams(localVarUrlObj, localVarQueryParameter);
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};

            return {
                url: toPathString(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
        /**
         * 
         * @param {number} [page] Zero-based page index (0..N)
         * @param {number} [size] The size of the page to be returned
         * @param {Array<string>} [sort] Sorting criteria in the format: property,(asc|desc). Default sort order is ascending. Multiple sort criteria are supported.
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        fetchAll2: async (page?: number, size?: number, sort?: Array<string>, options: RawAxiosRequestConfig = {}): Promise<RequestArgs> => {
            const localVarPath = `/v1/public/colors`;
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }

            const localVarRequestOptions = { method: 'GET', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;

            // authentication bearerAuth required
            // http bearer authentication required
            await setBearerAuthToObject(localVarHeaderParameter, configuration)

            if (page !== undefined) {
                localVarQueryParameter['page'] = page;
            }

            if (size !== undefined) {
                localVarQueryParameter['size'] = size;
            }

            if (sort) {
                localVarQueryParameter['sort'] = sort;
            }


    
            setSearchParams(localVarUrlObj, localVarQueryParameter);
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};

            return {
                url: toPathString(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
        /**
         * 
         * @param {number} id 
         * @param {ColorRequest} colorRequest 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        update6: async (id: number, colorRequest: ColorRequest, options: RawAxiosRequestConfig = {}): Promise<RequestArgs> => {
            // verify required parameter 'id' is not null or undefined
            assertParamExists('update6', 'id', id)
            // verify required parameter 'colorRequest' is not null or undefined
            assertParamExists('update6', 'colorRequest', colorRequest)
            const localVarPath = `/v1/admin/colors/{id}`
                .replace(`{${"id"}}`, encodeURIComponent(String(id)));
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }

            const localVarRequestOptions = { method: 'PUT', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;

            // authentication bearerAuth required
            // http bearer authentication required
            await setBearerAuthToObject(localVarHeaderParameter, configuration)


    
            localVarHeaderParameter['Content-Type'] = 'application/json';

            setSearchParams(localVarUrlObj, localVarQueryParameter);
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};
            localVarRequestOptions.data = serializeDataIfNeeded(colorRequest, localVarRequestOptions, configuration)

            return {
                url: toPathString(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
    }
};

/**
 * ColorControllerApi - functional programming interface
 * @export
 */
export const ColorControllerApiFp = function(configuration?: Configuration) {
    const localVarAxiosParamCreator = ColorControllerApiAxiosParamCreator(configuration)
    return {
        /**
         * 
         * @param {ColorRequest} colorRequest 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async create7(colorRequest: ColorRequest, options?: RawAxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<ApiResponseColorResponse>> {
            const localVarAxiosArgs = await localVarAxiosParamCreator.create7(colorRequest, options);
            const localVarOperationServerIndex = configuration?.serverIndex ?? 0;
            const localVarOperationServerBasePath = operationServerMap['ColorControllerApi.create7']?.[localVarOperationServerIndex]?.url;
            return (axios, basePath) => createRequestFunction(localVarAxiosArgs, globalAxios, BASE_PATH, configuration)(axios, localVarOperationServerBasePath || basePath);
        },
        /**
         * 
         * @param {number} id 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async delete9(id: number, options?: RawAxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<ApiResponseVoid>> {
            const localVarAxiosArgs = await localVarAxiosParamCreator.delete9(id, options);
            const localVarOperationServerIndex = configuration?.serverIndex ?? 0;
            const localVarOperationServerBasePath = operationServerMap['ColorControllerApi.delete9']?.[localVarOperationServerIndex]?.url;
            return (axios, basePath) => createRequestFunction(localVarAxiosArgs, globalAxios, BASE_PATH, configuration)(axios, localVarOperationServerBasePath || basePath);
        },
        /**
         * 
         * @param {number} [page] Zero-based page index (0..N)
         * @param {number} [size] The size of the page to be returned
         * @param {Array<string>} [sort] Sorting criteria in the format: property,(asc|desc). Default sort order is ascending. Multiple sort criteria are supported.
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async fetchAll2(page?: number, size?: number, sort?: Array<string>, options?: RawAxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<ApiResponsePageResponseColorResponse>> {
            const localVarAxiosArgs = await localVarAxiosParamCreator.fetchAll2(page, size, sort, options);
            const localVarOperationServerIndex = configuration?.serverIndex ?? 0;
            const localVarOperationServerBasePath = operationServerMap['ColorControllerApi.fetchAll2']?.[localVarOperationServerIndex]?.url;
            return (axios, basePath) => createRequestFunction(localVarAxiosArgs, globalAxios, BASE_PATH, configuration)(axios, localVarOperationServerBasePath || basePath);
        },
        /**
         * 
         * @param {number} id 
         * @param {ColorRequest} colorRequest 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async update6(id: number, colorRequest: ColorRequest, options?: RawAxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<ApiResponseColorResponse>> {
            const localVarAxiosArgs = await localVarAxiosParamCreator.update6(id, colorRequest, options);
            const localVarOperationServerIndex = configuration?.serverIndex ?? 0;
            const localVarOperationServerBasePath = operationServerMap['ColorControllerApi.update6']?.[localVarOperationServerIndex]?.url;
            return (axios, basePath) => createRequestFunction(localVarAxiosArgs, globalAxios, BASE_PATH, configuration)(axios, localVarOperationServerBasePath || basePath);
        },
    }
};

/**
 * ColorControllerApi - factory interface
 * @export
 */
export const ColorControllerApiFactory = function (configuration?: Configuration, basePath?: string, axios?: AxiosInstance) {
    const localVarFp = ColorControllerApiFp(configuration)
    return {
        /**
         * 
         * @param {ColorControllerApiCreate7Request} requestParameters Request parameters.
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        create7(requestParameters: ColorControllerApiCreate7Request, options?: RawAxiosRequestConfig): AxiosPromise<ApiResponseColorResponse> {
            return localVarFp.create7(requestParameters.colorRequest, options).then((request) => request(axios, basePath));
        },
        /**
         * 
         * @param {ColorControllerApiDelete9Request} requestParameters Request parameters.
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        delete9(requestParameters: ColorControllerApiDelete9Request, options?: RawAxiosRequestConfig): AxiosPromise<ApiResponseVoid> {
            return localVarFp.delete9(requestParameters.id, options).then((request) => request(axios, basePath));
        },
        /**
         * 
         * @param {ColorControllerApiFetchAll2Request} requestParameters Request parameters.
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        fetchAll2(requestParameters: ColorControllerApiFetchAll2Request = {}, options?: RawAxiosRequestConfig): AxiosPromise<ApiResponsePageResponseColorResponse> {
            return localVarFp.fetchAll2(requestParameters.page, requestParameters.size, requestParameters.sort, options).then((request) => request(axios, basePath));
        },
        /**
         * 
         * @param {ColorControllerApiUpdate6Request} requestParameters Request parameters.
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        update6(requestParameters: ColorControllerApiUpdate6Request, options?: RawAxiosRequestConfig): AxiosPromise<ApiResponseColorResponse> {
            return localVarFp.update6(requestParameters.id, requestParameters.colorRequest, options).then((request) => request(axios, basePath));
        },
    };
};

/**
 * Request parameters for create7 operation in ColorControllerApi.
 * @export
 * @interface ColorControllerApiCreate7Request
 */
export interface ColorControllerApiCreate7Request {
    /**
     * 
     * @type {ColorRequest}
     * @memberof ColorControllerApiCreate7
     */
    readonly colorRequest: ColorRequest
}

/**
 * Request parameters for delete9 operation in ColorControllerApi.
 * @export
 * @interface ColorControllerApiDelete9Request
 */
export interface ColorControllerApiDelete9Request {
    /**
     * 
     * @type {number}
     * @memberof ColorControllerApiDelete9
     */
    readonly id: number
}

/**
 * Request parameters for fetchAll2 operation in ColorControllerApi.
 * @export
 * @interface ColorControllerApiFetchAll2Request
 */
export interface ColorControllerApiFetchAll2Request {
    /**
     * Zero-based page index (0..N)
     * @type {number}
     * @memberof ColorControllerApiFetchAll2
     */
    readonly page?: number

    /**
     * The size of the page to be returned
     * @type {number}
     * @memberof ColorControllerApiFetchAll2
     */
    readonly size?: number

    /**
     * Sorting criteria in the format: property,(asc|desc). Default sort order is ascending. Multiple sort criteria are supported.
     * @type {Array<string>}
     * @memberof ColorControllerApiFetchAll2
     */
    readonly sort?: Array<string>
}

/**
 * Request parameters for update6 operation in ColorControllerApi.
 * @export
 * @interface ColorControllerApiUpdate6Request
 */
export interface ColorControllerApiUpdate6Request {
    /**
     * 
     * @type {number}
     * @memberof ColorControllerApiUpdate6
     */
    readonly id: number

    /**
     * 
     * @type {ColorRequest}
     * @memberof ColorControllerApiUpdate6
     */
    readonly colorRequest: ColorRequest
}

/**
 * ColorControllerApi - object-oriented interface
 * @export
 * @class ColorControllerApi
 * @extends {BaseAPI}
 */
export class ColorControllerApi extends BaseAPI {
    /**
     * 
     * @param {ColorControllerApiCreate7Request} requestParameters Request parameters.
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof ColorControllerApi
     */
    public create7(requestParameters: ColorControllerApiCreate7Request, options?: RawAxiosRequestConfig) {
        return ColorControllerApiFp(this.configuration).create7(requestParameters.colorRequest, options).then((request) => request(this.axios, this.basePath));
    }

    /**
     * 
     * @param {ColorControllerApiDelete9Request} requestParameters Request parameters.
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof ColorControllerApi
     */
    public delete9(requestParameters: ColorControllerApiDelete9Request, options?: RawAxiosRequestConfig) {
        return ColorControllerApiFp(this.configuration).delete9(requestParameters.id, options).then((request) => request(this.axios, this.basePath));
    }

    /**
     * 
     * @param {ColorControllerApiFetchAll2Request} requestParameters Request parameters.
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof ColorControllerApi
     */
    public fetchAll2(requestParameters: ColorControllerApiFetchAll2Request = {}, options?: RawAxiosRequestConfig) {
        return ColorControllerApiFp(this.configuration).fetchAll2(requestParameters.page, requestParameters.size, requestParameters.sort, options).then((request) => request(this.axios, this.basePath));
    }

    /**
     * 
     * @param {ColorControllerApiUpdate6Request} requestParameters Request parameters.
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof ColorControllerApi
     */
    public update6(requestParameters: ColorControllerApiUpdate6Request, options?: RawAxiosRequestConfig) {
        return ColorControllerApiFp(this.configuration).update6(requestParameters.id, requestParameters.colorRequest, options).then((request) => request(this.axios, this.basePath));
    }
}

