/* tslint:disable */
/* eslint-disable */
/**
 * Spring-Adam-Store
 * Api Service
 *
 * The version of the OpenAPI document: v1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


import type { Configuration } from '../configuration';
import type { AxiosPromise, AxiosInstance, RawAxiosRequestConfig } from 'axios';
import globalAxios from 'axios';
// Some imports not used depending on template conditions
// @ts-ignore
import { DUMMY_BASE_URL, assertParamExists, setApiKeyToObject, setBasicAuthToObject, setBearerAuthToObject, setOAuthToObject, setSearchParams, serializeDataIfNeeded, toPathString, createRequestFunction } from '../common';
// @ts-ignore
import { BASE_PATH, COLLECTION_FORMATS, type RequestArgs, BaseAPI, RequiredError, operationServerMap } from '../base';
// @ts-ignore
import type { ApiResponseDistrictResponse } from '../models';
// @ts-ignore
import type { ApiResponsePageResponseDistrictResponse } from '../models';
// @ts-ignore
import type { ApiResponsePageResponseWardResponse } from '../models';
/**
 * DistrictControllerApi - axios parameter creator
 * @export
 */
export const DistrictControllerApiAxiosParamCreator = function (configuration?: Configuration) {
    return {
        /**
         * 
         * @param {number} [page] Zero-based page index (0..N)
         * @param {number} [size] The size of the page to be returned
         * @param {Array<string>} [sort] Sorting criteria in the format: property,(asc|desc). Default sort order is ascending. Multiple sort criteria are supported.
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        fetchAll7: async (page?: number, size?: number, sort?: Array<string>, options: RawAxiosRequestConfig = {}): Promise<RequestArgs> => {
            const localVarPath = `/v1/private/districts`;
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }

            const localVarRequestOptions = { method: 'GET', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;

            // authentication bearerAuth required
            // http bearer authentication required
            await setBearerAuthToObject(localVarHeaderParameter, configuration)

            if (page !== undefined) {
                localVarQueryParameter['page'] = page;
            }

            if (size !== undefined) {
                localVarQueryParameter['size'] = size;
            }

            if (sort) {
                localVarQueryParameter['sort'] = sort;
            }


    
            setSearchParams(localVarUrlObj, localVarQueryParameter);
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};

            return {
                url: toPathString(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
        /**
         * 
         * @param {number} id 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        fetchById5: async (id: number, options: RawAxiosRequestConfig = {}): Promise<RequestArgs> => {
            // verify required parameter 'id' is not null or undefined
            assertParamExists('fetchById5', 'id', id)
            const localVarPath = `/v1/private/districts/{id}`
                .replace(`{${"id"}}`, encodeURIComponent(String(id)));
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }

            const localVarRequestOptions = { method: 'GET', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;

            // authentication bearerAuth required
            // http bearer authentication required
            await setBearerAuthToObject(localVarHeaderParameter, configuration)


    
            setSearchParams(localVarUrlObj, localVarQueryParameter);
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};

            return {
                url: toPathString(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
        /**
         * API dùng để lấy danh sách wards theo district
         * @param {number} districtId 
         * @param {number} [page] Zero-based page index (0..N)
         * @param {number} [size] The size of the page to be returned
         * @param {Array<string>} [sort] Sorting criteria in the format: property,(asc|desc). Default sort order is ascending. Multiple sort criteria are supported.
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        fetchWardsByDistrict: async (districtId: number, page?: number, size?: number, sort?: Array<string>, options: RawAxiosRequestConfig = {}): Promise<RequestArgs> => {
            // verify required parameter 'districtId' is not null or undefined
            assertParamExists('fetchWardsByDistrict', 'districtId', districtId)
            const localVarPath = `/v1/private/districts/{districtId}/wards`
                .replace(`{${"districtId"}}`, encodeURIComponent(String(districtId)));
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }

            const localVarRequestOptions = { method: 'GET', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;

            // authentication bearerAuth required
            // http bearer authentication required
            await setBearerAuthToObject(localVarHeaderParameter, configuration)

            if (page !== undefined) {
                localVarQueryParameter['page'] = page;
            }

            if (size !== undefined) {
                localVarQueryParameter['size'] = size;
            }

            if (sort) {
                localVarQueryParameter['sort'] = sort;
            }


    
            setSearchParams(localVarUrlObj, localVarQueryParameter);
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};

            return {
                url: toPathString(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
    }
};

/**
 * DistrictControllerApi - functional programming interface
 * @export
 */
export const DistrictControllerApiFp = function(configuration?: Configuration) {
    const localVarAxiosParamCreator = DistrictControllerApiAxiosParamCreator(configuration)
    return {
        /**
         * 
         * @param {number} [page] Zero-based page index (0..N)
         * @param {number} [size] The size of the page to be returned
         * @param {Array<string>} [sort] Sorting criteria in the format: property,(asc|desc). Default sort order is ascending. Multiple sort criteria are supported.
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async fetchAll7(page?: number, size?: number, sort?: Array<string>, options?: RawAxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<ApiResponsePageResponseDistrictResponse>> {
            const localVarAxiosArgs = await localVarAxiosParamCreator.fetchAll7(page, size, sort, options);
            const localVarOperationServerIndex = configuration?.serverIndex ?? 0;
            const localVarOperationServerBasePath = operationServerMap['DistrictControllerApi.fetchAll7']?.[localVarOperationServerIndex]?.url;
            return (axios, basePath) => createRequestFunction(localVarAxiosArgs, globalAxios, BASE_PATH, configuration)(axios, localVarOperationServerBasePath || basePath);
        },
        /**
         * 
         * @param {number} id 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async fetchById5(id: number, options?: RawAxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<ApiResponseDistrictResponse>> {
            const localVarAxiosArgs = await localVarAxiosParamCreator.fetchById5(id, options);
            const localVarOperationServerIndex = configuration?.serverIndex ?? 0;
            const localVarOperationServerBasePath = operationServerMap['DistrictControllerApi.fetchById5']?.[localVarOperationServerIndex]?.url;
            return (axios, basePath) => createRequestFunction(localVarAxiosArgs, globalAxios, BASE_PATH, configuration)(axios, localVarOperationServerBasePath || basePath);
        },
        /**
         * API dùng để lấy danh sách wards theo district
         * @param {number} districtId 
         * @param {number} [page] Zero-based page index (0..N)
         * @param {number} [size] The size of the page to be returned
         * @param {Array<string>} [sort] Sorting criteria in the format: property,(asc|desc). Default sort order is ascending. Multiple sort criteria are supported.
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async fetchWardsByDistrict(districtId: number, page?: number, size?: number, sort?: Array<string>, options?: RawAxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<ApiResponsePageResponseWardResponse>> {
            const localVarAxiosArgs = await localVarAxiosParamCreator.fetchWardsByDistrict(districtId, page, size, sort, options);
            const localVarOperationServerIndex = configuration?.serverIndex ?? 0;
            const localVarOperationServerBasePath = operationServerMap['DistrictControllerApi.fetchWardsByDistrict']?.[localVarOperationServerIndex]?.url;
            return (axios, basePath) => createRequestFunction(localVarAxiosArgs, globalAxios, BASE_PATH, configuration)(axios, localVarOperationServerBasePath || basePath);
        },
    }
};

/**
 * DistrictControllerApi - factory interface
 * @export
 */
export const DistrictControllerApiFactory = function (configuration?: Configuration, basePath?: string, axios?: AxiosInstance) {
    const localVarFp = DistrictControllerApiFp(configuration)
    return {
        /**
         * 
         * @param {DistrictControllerApiFetchAll7Request} requestParameters Request parameters.
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        fetchAll7(requestParameters: DistrictControllerApiFetchAll7Request = {}, options?: RawAxiosRequestConfig): AxiosPromise<ApiResponsePageResponseDistrictResponse> {
            return localVarFp.fetchAll7(requestParameters.page, requestParameters.size, requestParameters.sort, options).then((request) => request(axios, basePath));
        },
        /**
         * 
         * @param {DistrictControllerApiFetchById5Request} requestParameters Request parameters.
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        fetchById5(requestParameters: DistrictControllerApiFetchById5Request, options?: RawAxiosRequestConfig): AxiosPromise<ApiResponseDistrictResponse> {
            return localVarFp.fetchById5(requestParameters.id, options).then((request) => request(axios, basePath));
        },
        /**
         * API dùng để lấy danh sách wards theo district
         * @param {DistrictControllerApiFetchWardsByDistrictRequest} requestParameters Request parameters.
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        fetchWardsByDistrict(requestParameters: DistrictControllerApiFetchWardsByDistrictRequest, options?: RawAxiosRequestConfig): AxiosPromise<ApiResponsePageResponseWardResponse> {
            return localVarFp.fetchWardsByDistrict(requestParameters.districtId, requestParameters.page, requestParameters.size, requestParameters.sort, options).then((request) => request(axios, basePath));
        },
    };
};

/**
 * Request parameters for fetchAll7 operation in DistrictControllerApi.
 * @export
 * @interface DistrictControllerApiFetchAll7Request
 */
export interface DistrictControllerApiFetchAll7Request {
    /**
     * Zero-based page index (0..N)
     * @type {number}
     * @memberof DistrictControllerApiFetchAll7
     */
    readonly page?: number

    /**
     * The size of the page to be returned
     * @type {number}
     * @memberof DistrictControllerApiFetchAll7
     */
    readonly size?: number

    /**
     * Sorting criteria in the format: property,(asc|desc). Default sort order is ascending. Multiple sort criteria are supported.
     * @type {Array<string>}
     * @memberof DistrictControllerApiFetchAll7
     */
    readonly sort?: Array<string>
}

/**
 * Request parameters for fetchById5 operation in DistrictControllerApi.
 * @export
 * @interface DistrictControllerApiFetchById5Request
 */
export interface DistrictControllerApiFetchById5Request {
    /**
     * 
     * @type {number}
     * @memberof DistrictControllerApiFetchById5
     */
    readonly id: number
}

/**
 * Request parameters for fetchWardsByDistrict operation in DistrictControllerApi.
 * @export
 * @interface DistrictControllerApiFetchWardsByDistrictRequest
 */
export interface DistrictControllerApiFetchWardsByDistrictRequest {
    /**
     * 
     * @type {number}
     * @memberof DistrictControllerApiFetchWardsByDistrict
     */
    readonly districtId: number

    /**
     * Zero-based page index (0..N)
     * @type {number}
     * @memberof DistrictControllerApiFetchWardsByDistrict
     */
    readonly page?: number

    /**
     * The size of the page to be returned
     * @type {number}
     * @memberof DistrictControllerApiFetchWardsByDistrict
     */
    readonly size?: number

    /**
     * Sorting criteria in the format: property,(asc|desc). Default sort order is ascending. Multiple sort criteria are supported.
     * @type {Array<string>}
     * @memberof DistrictControllerApiFetchWardsByDistrict
     */
    readonly sort?: Array<string>
}

/**
 * DistrictControllerApi - object-oriented interface
 * @export
 * @class DistrictControllerApi
 * @extends {BaseAPI}
 */
export class DistrictControllerApi extends BaseAPI {
    /**
     * 
     * @param {DistrictControllerApiFetchAll7Request} requestParameters Request parameters.
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof DistrictControllerApi
     */
    public fetchAll7(requestParameters: DistrictControllerApiFetchAll7Request = {}, options?: RawAxiosRequestConfig) {
        return DistrictControllerApiFp(this.configuration).fetchAll7(requestParameters.page, requestParameters.size, requestParameters.sort, options).then((request) => request(this.axios, this.basePath));
    }

    /**
     * 
     * @param {DistrictControllerApiFetchById5Request} requestParameters Request parameters.
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof DistrictControllerApi
     */
    public fetchById5(requestParameters: DistrictControllerApiFetchById5Request, options?: RawAxiosRequestConfig) {
        return DistrictControllerApiFp(this.configuration).fetchById5(requestParameters.id, options).then((request) => request(this.axios, this.basePath));
    }

    /**
     * API dùng để lấy danh sách wards theo district
     * @param {DistrictControllerApiFetchWardsByDistrictRequest} requestParameters Request parameters.
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof DistrictControllerApi
     */
    public fetchWardsByDistrict(requestParameters: DistrictControllerApiFetchWardsByDistrictRequest, options?: RawAxiosRequestConfig) {
        return DistrictControllerApiFp(this.configuration).fetchWardsByDistrict(requestParameters.districtId, requestParameters.page, requestParameters.size, requestParameters.sort, options).then((request) => request(this.axios, this.basePath));
    }
}

