/* tslint:disable */
/* eslint-disable */
/**
 * Spring-Adam-Store
 * Api Service
 *
 * The version of the OpenAPI document: v1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


import type { Configuration } from '../configuration';
import type { AxiosPromise, AxiosInstance, RawAxiosRequestConfig } from 'axios';
import globalAxios from 'axios';
// Some imports not used depending on template conditions
// @ts-ignore
import { DUMMY_BASE_URL, assertParamExists, setApiKeyToObject, setBasicAuthToObject, setBearerAuthToObject, setOAuthToObject, setSearchParams, serializeDataIfNeeded, toPathString, createRequestFunction } from '../common';
// @ts-ignore
import { BASE_PATH, COLLECTION_FORMATS, type RequestArgs, BaseAPI, RequiredError, operationServerMap } from '../base';
/**
 * QrCodeControllerApi - axios parameter creator
 * @export
 */
export const QrCodeControllerApiAxiosParamCreator = function (configuration?: Configuration) {
    return {
        /**
         * 
         * @param {string} text 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        generateQRCode: async (text: string, options: RawAxiosRequestConfig = {}): Promise<RequestArgs> => {
            // verify required parameter 'text' is not null or undefined
            assertParamExists('generateQRCode', 'text', text)
            const localVarPath = `/v1/public/qrcode`;
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }

            const localVarRequestOptions = { method: 'GET', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;

            // authentication bearerAuth required
            // http bearer authentication required
            await setBearerAuthToObject(localVarHeaderParameter, configuration)

            if (text !== undefined) {
                localVarQueryParameter['text'] = text;
            }


    
            setSearchParams(localVarUrlObj, localVarQueryParameter);
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};

            return {
                url: toPathString(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
    }
};

/**
 * QrCodeControllerApi - functional programming interface
 * @export
 */
export const QrCodeControllerApiFp = function(configuration?: Configuration) {
    const localVarAxiosParamCreator = QrCodeControllerApiAxiosParamCreator(configuration)
    return {
        /**
         * 
         * @param {string} text 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async generateQRCode(text: string, options?: RawAxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<Array<string>>> {
            const localVarAxiosArgs = await localVarAxiosParamCreator.generateQRCode(text, options);
            const localVarOperationServerIndex = configuration?.serverIndex ?? 0;
            const localVarOperationServerBasePath = operationServerMap['QrCodeControllerApi.generateQRCode']?.[localVarOperationServerIndex]?.url;
            return (axios, basePath) => createRequestFunction(localVarAxiosArgs, globalAxios, BASE_PATH, configuration)(axios, localVarOperationServerBasePath || basePath);
        },
    }
};

/**
 * QrCodeControllerApi - factory interface
 * @export
 */
export const QrCodeControllerApiFactory = function (configuration?: Configuration, basePath?: string, axios?: AxiosInstance) {
    const localVarFp = QrCodeControllerApiFp(configuration)
    return {
        /**
         * 
         * @param {QrCodeControllerApiGenerateQRCodeRequest} requestParameters Request parameters.
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        generateQRCode(requestParameters: QrCodeControllerApiGenerateQRCodeRequest, options?: RawAxiosRequestConfig): AxiosPromise<Array<string>> {
            return localVarFp.generateQRCode(requestParameters.text, options).then((request) => request(axios, basePath));
        },
    };
};

/**
 * Request parameters for generateQRCode operation in QrCodeControllerApi.
 * @export
 * @interface QrCodeControllerApiGenerateQRCodeRequest
 */
export interface QrCodeControllerApiGenerateQRCodeRequest {
    /**
     * 
     * @type {string}
     * @memberof QrCodeControllerApiGenerateQRCode
     */
    readonly text: string
}

/**
 * QrCodeControllerApi - object-oriented interface
 * @export
 * @class QrCodeControllerApi
 * @extends {BaseAPI}
 */
export class QrCodeControllerApi extends BaseAPI {
    /**
     * 
     * @param {QrCodeControllerApiGenerateQRCodeRequest} requestParameters Request parameters.
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof QrCodeControllerApi
     */
    public generateQRCode(requestParameters: QrCodeControllerApiGenerateQRCodeRequest, options?: RawAxiosRequestConfig) {
        return QrCodeControllerApiFp(this.configuration).generateQRCode(requestParameters.text, options).then((request) => request(this.axios, this.basePath));
    }
}

