/* tslint:disable */
/* eslint-disable */
/**
 * Spring-Adam-Store
 * Api Service
 *
 * The version of the OpenAPI document: v1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


// May contain unused imports in some cases
// @ts-ignore
import type { ShippingFeeResponse } from './shipping-fee-response';

/**
 * 
 * @export
 * @interface ApiResponseShippingFeeResponse
 */
export interface ApiResponseShippingFeeResponse {
    /**
     * 
     * @type {number}
     * @memberof ApiResponseShippingFeeResponse
     */
    'code'?: number;
    /**
     * 
     * @type {string}
     * @memberof ApiResponseShippingFeeResponse
     */
    'message'?: string;
    /**
     * 
     * @type {ShippingFeeResponse}
     * @memberof ApiResponseShippingFeeResponse
     */
    'result'?: ShippingFeeResponse;
}

