/* tslint:disable */
/* eslint-disable */
/**
 * Spring-Adam-Store
 * Api Service
 *
 * The version of the OpenAPI document: v1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


// May contain unused imports in some cases
// @ts-ignore
import type { PageResponseOrderResponse } from './page-response-order-response';

/**
 * 
 * @export
 * @interface ApiResponsePageResponseOrderResponse
 */
export interface ApiResponsePageResponseOrderResponse {
    /**
     * 
     * @type {number}
     * @memberof ApiResponsePageResponseOrderResponse
     */
    'code'?: number;
    /**
     * 
     * @type {string}
     * @memberof ApiResponsePageResponseOrderResponse
     */
    'message'?: string;
    /**
     * 
     * @type {PageResponseOrderResponse}
     * @memberof ApiResponsePageResponseOrderResponse
     */
    'result'?: PageResponseOrderResponse;
}

