/* tslint:disable */
/* eslint-disable */
/**
 * Spring-Adam-Store
 * Api Service
 *
 * The version of the OpenAPI document: v1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


// May contain unused imports in some cases
// @ts-ignore
import type { PageResponseSizeResponse } from './page-response-size-response';

/**
 * 
 * @export
 * @interface ApiResponsePageResponseSizeResponse
 */
export interface ApiResponsePageResponseSizeResponse {
    /**
     * 
     * @type {number}
     * @memberof ApiResponsePageResponseSizeResponse
     */
    'code'?: number;
    /**
     * 
     * @type {string}
     * @memberof ApiResponsePageResponseSizeResponse
     */
    'message'?: string;
    /**
     * 
     * @type {PageResponseSizeResponse}
     * @memberof ApiResponsePageResponseSizeResponse
     */
    'result'?: PageResponseSizeResponse;
}

