/* tslint:disable */
/* eslint-disable */
/**
 * Spring-Adam-Store
 * Api Service
 *
 * The version of the OpenAPI document: v1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


// May contain unused imports in some cases
// @ts-ignore
import type { PageResponseAddressResponse } from './page-response-address-response';

/**
 * 
 * @export
 * @interface ApiResponsePageResponseAddressResponse
 */
export interface ApiResponsePageResponseAddressResponse {
    /**
     * 
     * @type {number}
     * @memberof ApiResponsePageResponseAddressResponse
     */
    'code'?: number;
    /**
     * 
     * @type {string}
     * @memberof ApiResponsePageResponseAddressResponse
     */
    'message'?: string;
    /**
     * 
     * @type {PageResponseAddressResponse}
     * @memberof ApiResponsePageResponseAddressResponse
     */
    'result'?: PageResponseAddressResponse;
}

