/* tslint:disable */
/* eslint-disable */
/**
 * Spring-Adam-Store
 * Api Service
 *
 * The version of the OpenAPI document: v1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


// May contain unused imports in some cases
// @ts-ignore
import type { PageResponseCartItemResponse } from './page-response-cart-item-response';

/**
 * 
 * @export
 * @interface ApiResponsePageResponseCartItemResponse
 */
export interface ApiResponsePageResponseCartItemResponse {
    /**
     * 
     * @type {number}
     * @memberof ApiResponsePageResponseCartItemResponse
     */
    'code'?: number;
    /**
     * 
     * @type {string}
     * @memberof ApiResponsePageResponseCartItemResponse
     */
    'message'?: string;
    /**
     * 
     * @type {PageResponseCartItemResponse}
     * @memberof ApiResponsePageResponseCartItemResponse
     */
    'result'?: PageResponseCartItemResponse;
}

