/* tslint:disable */
/* eslint-disable */
/**
 * Spring-Adam-Store
 * Api Service
 *
 * The version of the OpenAPI document: v1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


// May contain unused imports in some cases
// @ts-ignore
import type { PageResponsePaymentHistoryResponse } from './page-response-payment-history-response';

/**
 * 
 * @export
 * @interface ApiResponsePageResponsePaymentHistoryResponse
 */
export interface ApiResponsePageResponsePaymentHistoryResponse {
    /**
     * 
     * @type {number}
     * @memberof ApiResponsePageResponsePaymentHistoryResponse
     */
    'code'?: number;
    /**
     * 
     * @type {string}
     * @memberof ApiResponsePageResponsePaymentHistoryResponse
     */
    'message'?: string;
    /**
     * 
     * @type {PageResponsePaymentHistoryResponse}
     * @memberof ApiResponsePageResponsePaymentHistoryResponse
     */
    'result'?: PageResponsePaymentHistoryResponse;
}

