/* tslint:disable */
/* eslint-disable */
/**
 * Spring-Adam-Store
 * Api Service
 *
 * The version of the OpenAPI document: v1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


// May contain unused imports in some cases
// @ts-ignore
import type { FileResponse } from './file-response';

/**
 * 
 * @export
 * @interface ApiResponseListFileResponse
 */
export interface ApiResponseListFileResponse {
    /**
     * 
     * @type {number}
     * @memberof ApiResponseListFileResponse
     */
    'code'?: number;
    /**
     * 
     * @type {string}
     * @memberof ApiResponseListFileResponse
     */
    'message'?: string;
    /**
     * 
     * @type {Array<FileResponse>}
     * @memberof ApiResponseListFileResponse
     */
    'result'?: Array<FileResponse>;
}

