/* tslint:disable */
/* eslint-disable */
/**
 * Spring-Adam-Store
 * Api Service
 *
 * The version of the OpenAPI document: v1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


// May contain unused imports in some cases
// @ts-ignore
import type { ConversationResponse } from './conversation-response';

/**
 * 
 * @export
 * @interface ApiResponseConversationResponse
 */
export interface ApiResponseConversationResponse {
    /**
     * 
     * @type {number}
     * @memberof ApiResponseConversationResponse
     */
    'code'?: number;
    /**
     * 
     * @type {string}
     * @memberof ApiResponseConversationResponse
     */
    'message'?: string;
    /**
     * 
     * @type {ConversationResponse}
     * @memberof ApiResponseConversationResponse
     */
    'result'?: ConversationResponse;
}

