/* tslint:disable */
/* eslint-disable */
/**
 * Spring-Adam-Store
 * Api Service
 *
 * The version of the OpenAPI document: v1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


// May contain unused imports in some cases
// @ts-ignore
import type { PageResponseColorResponse } from './page-response-color-response';

/**
 * 
 * @export
 * @interface ApiResponsePageResponseColorResponse
 */
export interface ApiResponsePageResponseColorResponse {
    /**
     * 
     * @type {number}
     * @memberof ApiResponsePageResponseColorResponse
     */
    'code'?: number;
    /**
     * 
     * @type {string}
     * @memberof ApiResponsePageResponseColorResponse
     */
    'message'?: string;
    /**
     * 
     * @type {PageResponseColorResponse}
     * @memberof ApiResponsePageResponseColorResponse
     */
    'result'?: PageResponseColorResponse;
}

