/* tslint:disable */
/* eslint-disable */
/**
 * Spring-Adam-Store
 * Api Service
 *
 * The version of the OpenAPI document: v1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


// May contain unused imports in some cases
// @ts-ignore
import type { PermissionResponse } from './permission-response';

/**
 * 
 * @export
 * @interface ApiResponsePermissionResponse
 */
export interface ApiResponsePermissionResponse {
    /**
     * 
     * @type {number}
     * @memberof ApiResponsePermissionResponse
     */
    'code'?: number;
    /**
     * 
     * @type {string}
     * @memberof ApiResponsePermissionResponse
     */
    'message'?: string;
    /**
     * 
     * @type {PermissionResponse}
     * @memberof ApiResponsePermissionResponse
     */
    'result'?: PermissionResponse;
}

