/* tslint:disable */
/* eslint-disable */
/**
 * Spring-Adam-Store
 * Api Service
 *
 * The version of the OpenAPI document: v1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


// May contain unused imports in some cases
// @ts-ignore
import type { VNPayResponse } from './vnpay-response';

/**
 * 
 * @export
 * @interface ApiResponseVNPayResponse
 */
export interface ApiResponseVNPayResponse {
    /**
     * 
     * @type {number}
     * @memberof ApiResponseVNPayResponse
     */
    'code'?: number;
    /**
     * 
     * @type {string}
     * @memberof ApiResponseVNPayResponse
     */
    'message'?: string;
    /**
     * 
     * @type {VNPayResponse}
     * @memberof ApiResponseVNPayResponse
     */
    'result'?: VNPayResponse;
}

