/* tslint:disable */
/* eslint-disable */
/**
 * Spring-Adam-Store
 * Api Service
 *
 * The version of the OpenAPI document: v1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


// May contain unused imports in some cases
// @ts-ignore
import type { CartItemResponse } from './cart-item-response';

/**
 * 
 * @export
 * @interface ApiResponseCartItemResponse
 */
export interface ApiResponseCartItemResponse {
    /**
     * 
     * @type {number}
     * @memberof ApiResponseCartItemResponse
     */
    'code'?: number;
    /**
     * 
     * @type {string}
     * @memberof ApiResponseCartItemResponse
     */
    'message'?: string;
    /**
     * 
     * @type {CartItemResponse}
     * @memberof ApiResponseCartItemResponse
     */
    'result'?: CartItemResponse;
}

