/* tslint:disable */
/* eslint-disable */
/**
 * Spring-Adam-Store
 * Api Service
 *
 * The version of the OpenAPI document: v1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


// May contain unused imports in some cases
// @ts-ignore
import type { PageResponseProvinceResponse } from './page-response-province-response';

/**
 * 
 * @export
 * @interface ApiResponsePageResponseProvinceResponse
 */
export interface ApiResponsePageResponseProvinceResponse {
    /**
     * 
     * @type {number}
     * @memberof ApiResponsePageResponseProvinceResponse
     */
    'code'?: number;
    /**
     * 
     * @type {string}
     * @memberof ApiResponsePageResponseProvinceResponse
     */
    'message'?: string;
    /**
     * 
     * @type {PageResponseProvinceResponse}
     * @memberof ApiResponsePageResponseProvinceResponse
     */
    'result'?: PageResponseProvinceResponse;
}

