/* tslint:disable */
/* eslint-disable */
/**
 * Spring-Adam-Store
 * Api Service
 *
 * The version of the OpenAPI document: v1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */



/**
 * 
 * @export
 * @interface BranchUpdateRequest
 */
export interface BranchUpdateRequest {
    /**
     * 
     * @type {string}
     * @memberof BranchUpdateRequest
     */
    'name'?: string;
    /**
     * 
     * @type {string}
     * @memberof BranchUpdateRequest
     */
    'location'?: string;
    /**
     * 
     * @type {string}
     * @memberof BranchUpdateRequest
     */
    'phone'?: string;
}

