/* tslint:disable */
/* eslint-disable */
/**
 * Spring-Adam-Store
 * Api Service
 *
 * The version of the OpenAPI document: v1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


// May contain unused imports in some cases
// @ts-ignore
import type { ProductVariantBasic } from './product-variant-basic';

/**
 * 
 * @export
 * @interface CartItemResponse
 */
export interface CartItemResponse {
    /**
     * 
     * @type {number}
     * @memberof CartItemResponse
     */
    'id'?: number;
    /**
     * 
     * @type {number}
     * @memberof CartItemResponse
     */
    'price'?: number;
    /**
     * 
     * @type {number}
     * @memberof CartItemResponse
     */
    'quantity'?: number;
    /**
     * 
     * @type {ProductVariantBasic}
     * @memberof CartItemResponse
     */
    'productVariantBasic'?: ProductVariantBasic;
}

