/* tslint:disable */
/* eslint-disable */
/**
 * Spring-Adam-Store
 * Api Service
 *
 * The version of the OpenAPI document: v1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */



/**
 * 
 * @export
 * @interface EntityBasic
 */
export interface EntityBasic {
    /**
     * 
     * @type {number}
     * @memberof EntityBasic
     */
    'id'?: number;
    /**
     * 
     * @type {string}
     * @memberof EntityBasic
     */
    'name'?: string;
}

