/* tslint:disable */
/* eslint-disable */
/**
 * Spring-Adam-Store
 * Api Service
 *
 * The version of the OpenAPI document: v1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


// May contain unused imports in some cases
// @ts-ignore
import type { OrderItemRequest } from './order-item-request';

/**
 * 
 * @export
 * @interface OrderRequest
 */
export interface OrderRequest {
    /**
     * 
     * @type {number}
     * @memberof OrderRequest
     */
    'addressId': number;
    /**
     * 
     * @type {Array<OrderItemRequest>}
     * @memberof OrderRequest
     */
    'orderItems': Array<OrderItemRequest>;
    /**
     * 
     * @type {number}
     * @memberof OrderRequest
     */
    'promotionId'?: number;
    /**
     * 
     * @type {number}
     * @memberof OrderRequest
     */
    'shippingFee': number;
    /**
     * 
     * @type {string}
     * @memberof OrderRequest
     */
    'paymentMethod': OrderRequestPaymentMethodEnum;
}

export const OrderRequestPaymentMethodEnum = {
    VNPAY: 'VNPAY',
    CASH: 'CASH'
} as const;

export type OrderRequestPaymentMethodEnum = typeof OrderRequestPaymentMethodEnum[keyof typeof OrderRequestPaymentMethodEnum];


