/* tslint:disable */
/* eslint-disable */
/**
 * Spring-Adam-Store
 * Api Service
 *
 * The version of the OpenAPI document: v1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


// May contain unused imports in some cases
// @ts-ignore
import type { ProductResponse } from './product-response';

/**
 * 
 * @export
 * @interface PageResponseProductResponse
 */
export interface PageResponseProductResponse {
    /**
     * 
     * @type {number}
     * @memberof PageResponseProductResponse
     */
    'page'?: number;
    /**
     * 
     * @type {number}
     * @memberof PageResponseProductResponse
     */
    'size'?: number;
    /**
     * 
     * @type {number}
     * @memberof PageResponseProductResponse
     */
    'totalPages'?: number;
    /**
     * 
     * @type {number}
     * @memberof PageResponseProductResponse
     */
    'totalItems'?: number;
    /**
     * 
     * @type {Array<ProductResponse>}
     * @memberof PageResponseProductResponse
     */
    'items'?: Array<ProductResponse>;
}

