/* tslint:disable */
/* eslint-disable */
/**
 * Spring-Adam-Store
 * Api Service
 *
 * The version of the OpenAPI document: v1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */



/**
 * 
 * @export
 * @interface PermissionResponse
 */
export interface PermissionResponse {
    /**
     * 
     * @type {number}
     * @memberof PermissionResponse
     */
    'id'?: number;
    /**
     * 
     * @type {string}
     * @memberof PermissionResponse
     */
    'name'?: string;
    /**
     * 
     * @type {string}
     * @memberof PermissionResponse
     */
    'module'?: string;
    /**
     * 
     * @type {string}
     * @memberof PermissionResponse
     */
    'apiPath'?: string;
    /**
     * 
     * @type {string}
     * @memberof PermissionResponse
     */
    'method'?: string;
}

