/* tslint:disable */
/* eslint-disable */
/**
 * Spring-Adam-Store
 * Api Service
 *
 * The version of the OpenAPI document: v1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


// May contain unused imports in some cases
// @ts-ignore
import type { EntityBasic } from './entity-basic';

/**
 * 
 * @export
 * @interface ProductVariantResponse
 */
export interface ProductVariantResponse {
    /**
     * 
     * @type {number}
     * @memberof ProductVariantResponse
     */
    'id'?: number;
    /**
     * 
     * @type {number}
     * @memberof ProductVariantResponse
     */
    'price'?: number;
    /**
     * 
     * @type {number}
     * @memberof ProductVariantResponse
     */
    'quantity'?: number;
    /**
     * 
     * @type {boolean}
     * @memberof ProductVariantResponse
     */
    'isAvailable'?: boolean;
    /**
     * 
     * @type {string}
     * @memberof ProductVariantResponse
     */
    'imageUrl'?: string;
    /**
     * 
     * @type {string}
     * @memberof ProductVariantResponse
     */
    'status'?: ProductVariantResponseStatusEnum;
    /**
     * 
     * @type {EntityBasic}
     * @memberof ProductVariantResponse
     */
    'size'?: EntityBasic;
    /**
     * 
     * @type {EntityBasic}
     * @memberof ProductVariantResponse
     */
    'color'?: EntityBasic;
}

export const ProductVariantResponseStatusEnum = {
    ACTIVE: 'ACTIVE',
    INACTIVE: 'INACTIVE'
} as const;

export type ProductVariantResponseStatusEnum = typeof ProductVariantResponseStatusEnum[keyof typeof ProductVariantResponseStatusEnum];


