/* tslint:disable */
/* eslint-disable */
/**
 * Spring-Adam-Store
 * Api Service
 *
 * The version of the OpenAPI document: v1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


// May contain unused imports in some cases
// @ts-ignore
import type { VariantRequest } from './variant-request';

/**
 * 
 * @export
 * @interface ProductUpdateRequest
 */
export interface ProductUpdateRequest {
    /**
     * 
     * @type {string}
     * @memberof ProductUpdateRequest
     */
    'name'?: string;
    /**
     * 
     * @type {string}
     * @memberof ProductUpdateRequest
     */
    'description'?: string;
    /**
     * 
     * @type {number}
     * @memberof ProductUpdateRequest
     */
    'categoryId'?: number;
    /**
     * 
     * @type {Array<VariantRequest>}
     * @memberof ProductUpdateRequest
     */
    'variants': Array<VariantRequest>;
}

