/* tslint:disable */
/* eslint-disable */
/**
 * Spring-Adam-Store
 * Api Service
 *
 * The version of the OpenAPI document: v1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


// May contain unused imports in some cases
// @ts-ignore
import type { EntityBasic } from './entity-basic';

/**
 * 
 * @export
 * @interface ProductVariantBasic
 */
export interface ProductVariantBasic {
    /**
     * 
     * @type {number}
     * @memberof ProductVariantBasic
     */
    'id'?: number;
    /**
     * 
     * @type {EntityBasic}
     * @memberof ProductVariantBasic
     */
    'color'?: EntityBasic;
    /**
     * 
     * @type {EntityBasic}
     * @memberof ProductVariantBasic
     */
    'size'?: EntityBasic;
    /**
     * 
     * @type {EntityBasic}
     * @memberof ProductVariantBasic
     */
    'product'?: EntityBasic;
}

