/* tslint:disable */
/* eslint-disable */
/**
 * Spring-Adam-Store
 * Api Service
 *
 * The version of the OpenAPI document: v1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


// May contain unused imports in some cases
// @ts-ignore
import type { OrderItemRequest } from './order-item-request';

/**
 * 
 * @export
 * @interface ShippingRequest
 */
export interface ShippingRequest {
    /**
     * 
     * @type {number}
     * @memberof ShippingRequest
     */
    'addressId': number;
    /**
     * 
     * @type {Array<OrderItemRequest>}
     * @memberof ShippingRequest
     */
    'orderItems': Array<OrderItemRequest>;
}

